
'''hashtable /hashmap- type of data  structure that maps keys to its value pairs
it is used in dictionaries , hashtables store key values , the keys in a dictionary are generated by a hashing function
 there are  two ways  of creating a dictionary -using curly braces, -or using dict() function'''

my_dict =  {1:'dave',
                  2:'ava', 3:'steve', 4:'jesu' ,
            'fifth':'shikra', 'sixth':'mariam'}
print(my_dict)
print(type(my_dict))
#or
new_dict = dict(dave='oo1',ava='2')
print(new_dict['dave'])
print(new_dict)

#nested dictionaries
emp_details ={'employee':{'dave':{'ID':'001','salary':'20000','designation':'team lead'},
                          'ava':{'ID':'002','salary':'10000','designation':'team management'}}}
print(emp_details)

#performing operations on hash tables- access ,update and delete elements
my_dict =  {1:'dave',
                  2:'ava', 3:'steve', 7:'jesu' ,
            'fifth':'shikra', 'sixth':'mariam'}

print(my_dict[1])
# or
new_dict: dict(dave='oo1',ava='2')
print(new_dict['dave'])

print(my_dict.values())
print(my_dict.get(2))

for x in my_dict:
    print(x)


for x in my_dict.values():
    print(x)

for x,y in my_dict.items():
    print(x,y)

 #dictionaries  are mutable data types and you can update them as and when required
new_dict: dict(dave='oo1', ava='2')
new_dict['dave'] ='001'
new_dict['chris'] = '003'
new_dict['delaview'] = '0034'
print(new_dict)

#deleting
new_dict.pop('ava')
print(new_dict)

new_dict.popitem()
print(new_dict)

del new_dict['dave']
print(new_dict)

#converting dictionary to a dataframe
''' a DATAFRAME is a 2d  data structure that consists of columns of various  types.
it is a very similar  to dictionary  and you can convert it into pandas dataframe '''

emp_details ={'employee':{'dave':{'ID':'001','salary':'20000','designation':'team lead'},
                          'ava':{'ID':'002','salary':'10000','designation':'team management'}}}
print(emp_details)

''''import pandas as pd
df = pd.DataFrame(emp_details['employee'])
print(pd)
#the output  will be a table'''

import pandas as py
n = py.DataFrame(emp_details['employee'])
print(py)
